variable "app_environment" {}
variable "app_name" {}
variable "aws_region" {}
variable "host_header" {}
variable "repository_url" {}
variable "vpc_id" {}
variable "cluster_id" {}
variable "cluster_name" {}
variable "private_subnets" {}
variable "alb_security_group_id" {}
variable "alb_id" {}
variable "alb_arn" {}
variable "certificate_arn" {}
